version: 2
jobs:
  DevelopmentEnvironment:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - run:
         name: "Ejecucion App1" 
         command: |
           cd ./App1
           npm install
           yarn run build   
           ssh -o StrictHostKeyChecking=no ec2-user@3.235.152.80 "mkdir -p App1"
           scp -o StrictHostKeyChecking=no -r ./build/* ec2-user@3.235.152.80:~/App1
      - run:
         name: "Ejecucion App2" 
         command: |
           cd ./App2
           ssh -o StrictHostKeyChecking=no ec2-user@3.235.152.80 "mkdir -p App2"
           scp -o StrictHostKeyChecking=no -r ./* ec2-user@3.235.152.80:~/App2
  ProductionEnvironment:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - run:
         name: "Ejecucion App1" 
         command: |
           cd ./App1
           npm install
           yarn run build   
           ssh -o StrictHostKeyChecking=no ec2-user@3.94.81.164 "mkdir -p App1"
           scp -o StrictHostKeyChecking=no -r ./build/* ec2-user@3.94.81.164:~/App1
      - run:
         name: "Ejecucion App2" 
         command: |
           cd ./App2
           ssh -o StrictHostKeyChecking=no ec2-user@3.94.81.164 "mkdir -p App2"
           scp -o StrictHostKeyChecking=no -r ./* ec2-user@3.94.81.164:~/App2
workflows:
  version: 2
  build: 
    jobs:
      - DevelopmentEnvironment
      - request-testing:
          type: approval
          requires:
            - DevelopmentEnvironment
      - ProductionEnvironment:
          requires:
            - request-testing
