version: 2
jobs:
  ProductionEnvironment:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./App1/package.json" }}            
            - v1-dependencies-
            - v2-dependencies-{{ checksum "./App2/package.json" }}            
            - v2-dependencies-
      - run:
         name: "Ejecucion App1" 
         command: |
           cd ./App1
           npm install
           yarn run build   
           ssh -o StrictHostKeyChecking=no ec2-user@54.224.198.97 "mkdir -p App1"
           scp -o StrictHostKeyChecking=no -r ./build/* ec2-user@54.224.198.97:~/App1
      - run:
         name: "Ejecucion App2" 
         command: |
           cd ./App2
           npm install
           yarn run build   
           ssh -o StrictHostKeyChecking=no ec2-user@54.224.198.97 "mkdir -p App2"
           scp -o StrictHostKeyChecking=no -r ./build/* ec2-user@54.224.198.97:~/App2
      - run:
         name: "Archivo yaml" 
         command: |
           cd ./Configuracion
           scp -o StrictHostKeyChecking=no -r ./* ec2-user@54.224.198.97:~/
           ssh -o StrictHostKeyChecking=no ec2-user@54.224.198.97 "kubectl apply -f deployment.yaml"
      - save_cache:
          paths:
            - ./App1/node_modules
            - ./App2/node_modules
          key: v1-dependencies-{{ checksum "./App1/package.json" }}
          key: v2-dependencies-{{ checksum "./App2/package.json" }}
workflows:
  version: 2
  build: 
    jobs:
      - ProductionEnvironment