version: 2
jobs:
  build:
    docker:
      
      - image: circleci/node:8.10

    steps:
      - checkout
      
      - run: ls

  ProductionEnvironment:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo/App1/
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - run: yarn run build   
      - run:
         name: "Ejecucion" 
         command: |
           echo "A first hello"
           ls --all
           pwd 
           echo "Finished new"              
           scp -o StrictHostKeyChecking=no ./build ec2-user@3.85.234.255:~/App1
workflows:
  version: 2
  build: 
    jobs:
      - build: 
          filters:
            branches:
              only:
                - circleci-project-setup
      - request-testing:
          type: approval
          requires:
            - build
      - ProductionEnvironment:
          requires:
            - request-testing